### ISSUE TITLE
[SUGGESTION] Name folders by the resource the config files are for

### ISSUE THREAD

**Issue by tom-osborne** [QB-Configs/GABZ#1]
**Is your feature request related to a problem? Please describe.**
No

**Describe the feature you'd like**
Currently, the way this repository is set up, it is difficult to understand for which resources the config files are for. It would make things far more intuitive if you were to either name the config file by the resource or place them in a folder named as the resource.

E.g.
Gabz / PDM / qb-vehicleshop / config.lua

or
Gabz / PDM / qb-vehicleshop.lua

I.e. the following format:
[Creator] / [MLO] / [resource] / config.lua

**Describe alternatives you've considered**
The other way would be to keep an index in the readme, but thats an extra step for admin.

**Additional context**
N/A

**Comment by Irishstevie** [comment]
Love that <3
